server:
  port: 8852

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name:  feign-client

# 开启feign的熔断功能
feign:
  hystrix:
    enabled: true